### PR TITLE
Export weblocks/js/jquery:jquery-backend

### PR DESCRIPTION
**Pull request by ralt**
This lets me extend the jquery-backend with custom additional functions without having to copy paste the whole jquery backend.

### CODE REVIEW

**Comment by ralt** [comment]
In this current example I have, it lets me do this:

```
(defclass foo-js-backend (weblocks/js/jquery:jquery-backend)
  ())

(defmethod make-js-backend ((name (eql :foo)))
  (make-instance 'foo-js-backend))

(defmethod get-dependencies ((self foo-js-backend))
  (append (call-next-method)
	  (list (make-dependency "custom-functions.js"))))

(defapp foo
    :js-backend :foo)
```

**Comment by ralt** [comment]
Sorry, I missed the last bit this lets me do:

```
(defun make-wrapped-js-action (action)
  (format nil "return fooFunction(function() { ~a });" (make-js-action action)))
```

(With `fooFunction` being defined in custom-functions.js... although I wonder if I could just write it in parenscript now...)

**Comment by svetlyak40wt** [comment]
Thank you. By the way, you dont have ti define your own js backend to add some js code. 

Just define a get-dependencies method.

**Comment by ralt** [comment]
Which makes... total sense.

Thank you.

**Pull request closed without merging**
