### PR TITLE
quickstart: add gifs, add task at bottom and document how to build the doc

### PR DESCRIPTION
**Pull request by vindarel**
Hi !

My 2 cents :) Your quickstart really makes one want dive into Weblocks.

I thoughgt installing cl-launch was difficult but it's only a `apt-get install` away: => documented in a readme.

---

I couldn't build the documentation because of an error with your sphinxcontrib-cldomain (since the projects are forks they don't have issues, so posting here)

```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4.9
loading pickled environment... not yet created
Collecting Lisp docstrings from weblocks...
To load "sphinxcontrib.cldomain":
  Load 1 ASDF system:
    sphinxcontrib.cldomain
; Loading "sphinxcontrib.cldomain"
[… truncated …]
(push (pathname (concatenate 'string (uiop/os:getenv \\\"CLDOMAIN\\\") \\\"/\\\"))
                             asdf:*central-registry*)

(asdf:initialize-source-registry)
(asdf:require-system :quicklisp)

(let ((*standard-output* *error-output*))
  (quicklisp:quickload 'sphinxcontrib.cldomain))

(sphinxcontrib.cldomain:main)\"))")))
56: (SB-IMPL::TOPLEVEL-INIT)
57: ((FLET "WITHOUT-INTERRUPTS-BODY-6" :IN SB-EXT:SAVE-LISP-AND-DIE))
58: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))
Above backtrace due to this condition:
SET-DISPATCH-MACRO-CHARACTER would modify the standard readtable.
See also:
  The ANSI Standard, Section 2.1.1.2
  The ANSI Standard, Glossary entry for "standard readtable"
SET-DISPATCH-MACRO-CHARACTER would modify the standard readtable.
See also:
  The ANSI Standard, Section 2.1.1.2
  The ANSI Standard, Glossary entry for "standard readtable"
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions

Exception occurred:
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/usr/bin/cl-launch', '--init', '\n#-quicklisp\n(let ((quicklisp-init (merge-pathnames (make-pathname :name "setup"\n                                                      :type "lisp")\n                                       (concatenate \'string (uiop/os:getenv "QUICKLISP")\n                                                    "/"))))\n  (if (probe-file quicklisp-init)\n      (load quicklisp-init)\n      (error "Can\'t Find Quicklisp at ~a~%" quicklisp-init)))\n', '--init', '\n(push (pathname (concatenate \'string (uiop/os:getenv "CLDOMAIN") "/"))\n                             asdf:*central-registry*)\n', '--init', '(asdf:initialize-source-registry)', '--init', '(asdf:require-system :quicklisp)', '--init', "\n(let ((*standard-output* *error-output*))\n  (quicklisp:quickload 'sphinxcontrib.cldomain))\n", '--init', '(sphinxcontrib.cldomain:main)', '--', '--package', 'WEBLOCKS', '--system', 'weblocks', '--path', u'/home/vince/quicklisp/local-projects/weblocks/docs/source/../../']' returned non-zero exit status 99
The full traceback has been saved in /tmp/sphinx-err-RjS5xG.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:45: recipe for target 'html' failed
make: *** [html] Error 1
(weblocks)[~/quicklisp/local-projects/weblocks/docs]
```

Sphinx reported log:

```
# Sphinx version: 1.4.9
# Python version: 2.7.9 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/vince/.virtualenvs/weblocks/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/vince/.virtualenvs/weblocks/local/lib/python2.7/site-packages/sphinx/application.py", line 204, in __init__
    self._init_builder(self.buildername)
  File "/home/vince/.virtualenvs/weblocks/local/lib/python2.7/site-packages/sphinx/application.py", line 279, in _init_builder
    self.emit('builder-inited')
  File "/home/vince/.virtualenvs/weblocks/local/lib/python2.7/site-packages/sphinx/application.py", line 551, in emit
    results.append(callback(self, *args))
  File "/home/vince/.virtualenvs/weblocks/src/sphinxcontrib-cldomain/sphinxcontrib/cldomain.py", line 1015, in load_packages
    app.config.cl_debug)
  File "/home/vince/.virtualenvs/weblocks/src/sphinxcontrib-cldomain/sphinxcontrib/cldomain.py", line 888, in index_packages
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/usr/bin/cl-launch', '--init', '\n#-quicklisp\n(let ((quicklisp-init (merge-pathnames (make-pathname :name "setup"\n                                                      :type "lisp")\n                                       (concatenate \'string (uiop/os:getenv "QUICKLISP")\n                                                    "/"))))\n  (if (probe-file quicklisp-init)\n      (load quicklisp-init)\n      (error "Can\'t Find Quicklisp at ~a~%" quicklisp-init)))\n', '--init', '\n(push (pathname (concatenate \'string (uiop/os:getenv "CLDOMAIN") "/"))\n                             asdf:*central-registry*)\n', '--init', '(asdf:initialize-source-registry)', '--init', '(asdf:require-system :quicklisp)', '--init', "\n(let ((*standard-output* *error-output*))\n  (quicklisp:quickload 'sphinxcontrib.cldomain))\n", '--init', '(sphinxcontrib.cldomain:main)', '--', '--package', 'WEBLOCKS', '--system', 'weblocks', '--path', u'/home/vince/quicklisp/local-projects/weblocks/docs/source/../../']' returned non-zero exit status 99
```
maybe useful

```
$ env | grep QUICKLISP                
PWD=/home/vince/quicklisp/local-projects/weblocks/docs
```
and `$ env | grep CLDOMAIN`: nothing.

So I may suggest little tutorial improvements without building the doc.

Cheers !

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
Thank you, @vindarel!

Why did you decide to use old cldomain version, based on cl-launch?

I've rewrote it to use Roswell as an installer:

http://40ants.com/cldomain/

Could you please replace cl-launch installation with this link? Or just `ros install 40ants/cldomain`.

**Comment by svetlyak40wt** [comment]
Oh, I've forgot to replace `russell/sphinxcontrib-cldomain` to `40ants/sphinxcontrib-cldomain` in docs/requirements.txt. That is why it required a cl-launch.

**Comment by svetlyak40wt** [comment]
By the way, was you able to go through the quickstart guide?

**Comment by svetlyak40wt** [comment]
I've updated docs/requirements.txt in https://github.com/40ants/weblocks/commit/8a7a3c23ac41613dc6a9eea2aa1767f8855646dc

**Comment by vindarel** [comment]
> I've rewrote it to use Roswell as an installer

I was wondering why you hadn't :)  Actually I saw the good requirement in `requirement.IN`, and it was not in the `.txt` !

So I installed cldomain with Roswell and updated the python requirements. Now I get:

```
45: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SB-EXT:SAVE-LISP-AND-DIE))
46: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting

Exception occurred:
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/home/vince/.roswell/bin/cldomain', '--package', 'WEBLOCKS', '--system', 'weblocks', '--path', u'/home/vince/quicklisp/local-projects/weblocks/docs/source/../../']' returned non-zero exit status 1
```

Note that I'm not sure what to do with the configuration section: http://40ants.com/cldomain/#configuration It doesn't say where to put this, if it's important. I put it in `/docs/conf.py` (Sphinx default), only changing the name and packages list:

```
cl_systems = [{"name": "weblocks",
               "path": join(dirname(realpath(__file__)), "../"),
               "packages": ["weblocks"]}]
```

with no more success.


Yes I've been through the quickstart tutorial and it's really great ! I've been annoyed by the task that is added at the top of the list, not at the bottom (`push` vs adding to the end) and I'm eager to see more reactivity (not having to restart weblocks with two commands grouped in a progn, or being able to `setf tasks …` and see the changes, or this + `mark-dirty` or sthg). But I'm impressed and I'm hooked, I have to read the whole doc now.

btw, what are Weblocks limits ? Can it easily handle double data binding or nice urls ? (I've seen other continuations-based webframeworks (python's Nagare) being beautiful, except the urls that ressemble that of session IDs) (you didn't write about continuations in the doc yet).

I'm also very excited in the possibility to put the final website into Ceramic.

**edit**: I think the quickstart should define functions outside of the big `init-user-session`, to show that of course we can decouple stuff.

**Comment by vindarel** [comment]
I added gifs and fixes some typos.

I modified the examples to add a task to the bottom, so use `reverse` twice.

(and woops, looks like a bad rebase…)

**Comment by svetlyak40wt** [comment]
Gifs will be very helpful.

**Comment by svetlyak40wt** [comment]
Could you please post a complete output of the:

```
/home/vince/.roswell/bin/cldomain --package WEBLOCKS --system weblocks --path /home/vince/quicklisp/local-projects/weblocks/docs/source/../../
```

started in docs subdirectory?

**Comment by vindarel** [comment]
yes:

```
weblocks/docs]$ /home/vince/.roswell/bin/cldomain --package WEBLOCKS --system weblocks --path /home/vince/quicklisp/local-projects/weblocks/docs/source/../../
Unhandled ASDF/FIND-SYSTEM:FORMATTED-SYSTEM-DEFINITION-ERROR in thread #<SB-THREAD:THREAD
                                                                         "main thread" RUNNING

                                                                         {100295F983}>:
  OPERATION instances must only be created through MAKE-OPERATION.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {100295F983}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<ASDF/FIND-SYSTEM:FORMATTED-SYSTEM-DEFINITION-ERROR {100380C903}> #<unavailable argument>)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<ASDF/FIND-SYSTEM:FORMATTED-SYSTEM-DEFINITION-ERROR {100380C903}>)
2: (INVOKE-DEBUGGER #<ASDF/FIND-SYSTEM:FORMATTED-SYSTEM-DEFINITION-ERROR {100380C903}>)
3: (ERROR ASDF/FIND-SYSTEM:FORMATTED-SYSTEM-DEFINITION-ERROR :FORMAT-CONTROL "OPERATION instances must only be created through MAKE-OPERATION." :FORMAT-ARGUMENTS NIL)
4: (ASDF/FIND-SYSTEM:SYSDEF-ERROR "OPERATION instances must only be created through MAKE-OPERATION.")
5: ((:METHOD INITIALIZE-INSTANCE :BEFORE (ASDF/OPERATION:OPERATION)) #<ASDF/LISP-ACTION:LOAD-OP >) [fast-method]
6: ((LAMBDA NIL :IN "/home/vince/.roswell/bin/cldomain"))
7: (ASDF/INTERFACE::SYSTEM-LOADED-P CONTAINERS-SYSTEM::CL-CONTAINERS)
8: ((FLET #:WRAPPER60 :IN ASDF/INTERFACE::REQUIRED-SYSTEMS-LOADED-P) CONTAINERS-SYSTEM::CL-CONTAINERS)
9: (SB-KERNEL:%MAP-FOR-EFFECT-ARITY-1 #<CLOSURE (FLET #:WRAPPER60 :IN ASDF/INTERFACE::REQUIRED-SYSTEMS-LOADED-P) {7FFFF2F3608B}> (CONTAINERS-SYSTEM::CL-CONTAINERS CONTAINERS-SYSTEM::MOPTILITIES))
10: (ASDF/INTERFACE::REQUIRED-SYSTEMS-LOADED-P #<ASDF/INTERFACE::SYSTEM-CONNECTION "containers-moptilities">)
11: ((LAMBDA (ASDF/INTERFACE::CONNECTION) :IN ASDF/INTERFACE::LOAD-CONNECTED-SYSTEMS) #<ASDF/INTERFACE::SYSTEM-CONNECTION "containers-moptilities">)
12: (ASDF/INTERFACE:MAP-SYSTEM-CONNECTIONS #<FUNCTION (LAMBDA (ASDF/INTERFACE::CONNECTION) :IN ASDF/INTERFACE::LOAD-CONNECTED-SYSTEMS) {1007A1EC1B}>)
13: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/PACKAGE-INFERRED-SYSTEM:PACKAGE-INFERRED-SYSTEM "asdf"> :VERBOSE NIL)
14: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
15: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/PACKAGE-INFERRED-SYSTEM:PACKAGE-INFERRED-SYSTEM "asdf"> :VERBOSE NIL) [fast-method]
16: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP :ASDF :VERBOSE NIL)
17: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
18: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :ASDF :VERBOSE NIL) [fast-method]
19: (ASDF/OPERATE:LOAD-SYSTEM :ASDF :VERBOSE NIL)
20: (ASDF/UPGRADE:UPGRADE-ASDF)
21: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
22: (ASDF/CACHE:CALL-WITH-ASDF-CACHE #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1002CF7E0B}> :OVERRIDE NIL :KEY NIL)
23: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "salza2" :VERBOSE NIL) [fast-method]
24: (ASDF/OPERATE:LOAD-SYSTEM "salza2" :VERBOSE NIL)
25: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {1002CF501B}>)
26: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "salza2" :PROMPT NIL)
27: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "weblocks" :PROMPT NIL)
28: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unavailable argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100423225B}>) [fast-method]
29: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {10036AB733}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100423225B}>) [fast-method]
30: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) #<unavailable argument> :PROMPT NIL :SILENT T :VERBOSE NIL) [fast-method]
31: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {100422593B}>)
32: (MAIN "--package" "WEBLOCKS" "--system" "weblocks" "--path" "/home/vince/quicklisp/local-projects/weblocks/docs/source/../../")
33: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
34: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
35: (SB-EXT:EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL NIL)
36: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL)
37: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {10043B6413}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
38: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {10043B6413}> NIL)
39: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {10043B6413}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
40: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /home/vince/.roswell/bin/cldomain" {10043B1573}>)
41: (ROSWELL:SCRIPT "/home/vince/.roswell/bin/cldomain" "--package" "WEBLOCKS" "--system" "weblocks" "--path" "/home/vince/quicklisp/local-projects/weblocks/docs/source/../../")
42: (ROSWELL:RUN ((:EVAL "(ros:quicklisp)") (:SCRIPT "/home/vince/.roswell/bin/cldomain" "--package" "WEBLOCKS" "--system" "weblocks" "--path" "/home/vince/quicklisp/local-projects/weblocks/docs/source/../../") (:QUIT NIL)))
43: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/home/vince/.roswell/bin/cldomain" "--package" "WEBLOCKS" "--system" "weblocks" "--path" "/home/vince/quicklisp/local-projects/weblocks/docs/source/../../") (:QUIT NIL)))) #<NULL-LEXENV>)
44: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/home/vince/.roswell/bin/cldomain" "--package" "WEBLOCKS" "--system" "weblocks" "--path" "/home/vince/quicklisp/local-projects/weblocks/docs/source/../../") (:QUIT NIL)))))
45: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/home/vince/.linuxbrew/Cellar/roswell/17.6.9.79/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:eval\"(ros:quicklisp)\")(:script \"/home/vince/.roswell/bin/cldomain\"\"--package\"\"WEBLOCKS\"\"--system\"\"weblocks\"\"--path\"\"/home/vince/quicklisp/local-projects/weblocks/docs/source/../../\")(:quit ())))")))
46: (SB-IMPL::TOPLEVEL-INIT)
47: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SB-EXT:SAVE-LISP-AND-DIE))
48: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
(weblocks)[~/quicklisp/local-projects/weblocks/docs]$ 
```

**Comment by vindarel** [comment]
you wrote russian on this doc: http://40ants.com/weblocks/dependencies.html#notes :)

**Comment by svetlyak40wt** [comment]
> you wrote russian on this doc: http://40ants.com/weblocks/dependencies.html#notes :)

Yes, I know. My Weblocks branch is not ready yet. And most docs are the old one, transformed into reStructured text.

**Comment by svetlyak40wt** [comment]
> OPERATION instances must only be created through MAKE-OPERATION

Don't know why do you see this error. Which versions of SBCL, ASDF and Roswell are you using?

**Comment by vindarel** [comment]
SBCL 1.3.19

roswell 17.6.9.79

(asdf:asdf-version)
"3.2.1"

**Pull request closed without merging**
