### PR TITLE
fix missing *request-timeout* in request-handler2

### PR DESCRIPTION
**Pull request by vindarel**
this variable was defined in request-handler.lisp, which is not used
at the moment, and thus was missing in request-handler2.lisp.

### CODE REVIEW

**Comment by vindarel** [comment]
btw, it seems that we now need to keep up to date with weblocks-ui and maybe other systems (so putting the quickstart in its own project is not trivial). Could you commit your qlfile ? seems you didn't add it.

**Review by svetlyak40wt — APPROVED** [review]
Thank you for the fix. I've missed it because using CCL.

**Comment by svetlyak40wt** [comment]
I'm not using qlfile with weblocks. I use qlot only in the end-user applications. For example, now I'm building a personal CRM (for hackers). Here it's qlfile:

https://github.com/40ants/hacrm/blob/master/qlfile

But it is incomplete, because I have checkouts of many libraries in my `~/common-lisp/` directory.

**Comment by svetlyak40wt** [comment]
Now I'm thinking how to build and maintain a quicklisp repository for all systems related to weblocks. Investigating how does https://github.com/quicklisp/quicklisp-controller work.

**Comment by vindarel** [comment]
cool, I also think a QL dist would be great, because atm a user can not build a weblocks project. (If you want people to pressure the QL maintainer to produce more doc, count me in !^^)

I tried to load hacrm once but not with the qlfile yet.
A couple of weeks ago I managed to put the todomvc example into its own project, but it doesn't work any more because of the moving dependencies. If you want to do it and keep it up to date with your work on Weblocks, it would help others like me to build a project on it.

btw, I pinged you on gitter with a couple more questions/remarks :)

**Pull request merged**
