### PR TITLE
Large refactoring with moving all parts into the separate packages

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Now weblocks uses package inferred system ASDF class.

Much old code was removed or replaces with newer. Forget everything you did know about the Weblocks :)

### CODE REVIEW

**Comment by vindarel** [comment]
Impressive ! and I like the new names and packages.

Guess what I'll ask… is the quickstart good, can we reread it safely ? (It wasn't touched in this big refactoring).

**Comment by svetlyak40wt** [comment]
No, I didn't touched quickstart guide. I think, we need to include loading of the quickstart.lisp into the .travis.yml config and it will break any pull-requests.

**Comment by svetlyak40wt** [comment]
I'll fix it a little bit later, probably tomorrow.

**Comment by svetlyak40wt** [comment]
@vindarel I've fixed quickstart in pull https://github.com/40ants/weblocks/pull/9 and made more refactorings ;)

Now Travis will try to load quickstart.lisp and will block pull request untill quickstart will be fixed.

**Comment by vindarel** [comment]
Thanks ! I'll try again more confidently then.

**Pull request merged**
